<?php

function gpew_setparty_civicrm_post( $op, $objectName, $objectId, &$objectRef ) {

	if($op!='create' AND $op!='edit'){
		return;
	}
	if($objectName!='Individual'){
		return;
	}
		
	// set local party
	$params=array();
	$params[1] = array( $objectId, 'Integer');
	$civicrm_value_gpew_party_information = CRM_Core_DAO::executeQuery( "SELECT * FROM civicrm_value_gpew_party_information WHERE entity_id=%1", $params );
	$civicrm_value_gpew_party_information->fetch();		
	
	$party_ids=gpew_setparty_get_party_ids($objectId, $civicrm_value_gpew_party_information->override_local_party, NULL, $civicrm_value_gpew_party_information->local_party_id);
	gpew_setparty_set_party($objectId, $party_ids);
}

function gpew_setparty_get_party_ids($objectId, $override_local_party, $ward_ons_code=NULL, $local_party_contact_id=NULL){

	// is the override set?
	if($override_local_party) {
		//override is set
		//is there a local party contact id?
		if(is_numeric($local_party_contact_id)){
			
			//yes - the local party contact is should be as above
			//TODO: Check that this is a real local party 
		} else {
			//no - there is no local party
			$local_party_contact_id='';
		}
	} else {
		//override is not set, look up based on ward ons code
		//is the ward ons code there?
		if(is_null($ward_ons_code)){
			// if not, look it up from the area table
			$params=array( 1 => array( $objectId, 'Integer'));			
			$ward_ons_code_result=CRM_Core_DAO::executeQuery( "
				SELECT ward_ons_code
				FROM `civicrm_value_area_information`
				WHERE entity_id =%1
			", $params);
			$ward_ons_code_result->fetch();
			$ward_ons_code = $ward_ons_code_result->ward_ons_code;
		}
		if(strlen($ward_ons_code)){
		
			$params=array( 1 => array( $ward_ons_code, 'String'));
		 
			$local_party_contact_id_result=CRM_Core_DAO::executeQuery( "
				SELECT local_party_contact_id as id
				FROM civicrm_gpew_ward_local_party
				WHERE ward_ons_code = %1
			", $params);
			$local_party_contact_id_result->fetch();
			$local_party_contact_id=$local_party_contact_id_result->id;
		} else {
			$local_party_contact_id='';
		}
	}

	//how to work out regional party id
	//is there a numeric local party id?
	if(is_numeric($local_party_contact_id)){
		// the local party id is numeric
		$params=array( 1 => array( $local_party_contact_id, 'Integer'));
		$regional_party_contact_result=CRM_Core_DAO::executeQuery( "			
			SELECT rp.id as id
			FROM civicrm_contact AS rp
			JOIN civicrm_relationship AS cr ON rp.id=cr.contact_id_b
			JOIN civicrm_contact AS lp ON lp.id=cr.contact_id_a
			WHERE lp.id=%1 AND cr.relationship_type_id=23
		", $params
		);
		$regional_party_contact_result->fetch();
		$regional_party_contact_id = $regional_party_contact_result->id;		
	} else {
		
		// there is no numeric local party id
		$params=array( 1 => array( $objectId, 'Integer'));			
		$european_region_result=CRM_Core_DAO::executeQuery( "
			SELECT european_region as name
			FROM `civicrm_value_area_information`
			WHERE entity_id =%1
		", $params
		);
		$european_region_result->fetch();
		
		// this array translates from mapits names for EU regions to the ids as they are stored in CiviCRM
		
		$european_region_2_regional_party_translation=array(
			'South East' => 22318,
			'North West' => 22319,
			'North East' => 22320,
			'East Midlands' => 22321,
			'Eastern' => 22322,
			'London' => 22323,
			'Yorkshire and the Humber' => 22324,
			'South West' => 22325,
			'West Midlands' => 22326,
			'Wales' =>	22327
		);
		
		if(in_array ( $european_region_result->name , array_keys($european_region_2_regional_party_translation))) {
			$regional_party_contact_id=$european_region_2_regional_party_translation[$european_region_result->name];
		} else {
			$regional_party_contact_id='';
		}
	}
	return array(
		'local_party_contact_id'=>$local_party_contact_id,
		'regional_party_contact_id'=>$regional_party_contact_id
	);	
}

function gpew_setparty_set_party($objectId, $party_ids){
	
	//set the local party id
	
	//if we are overriding the local party, then we shouldn't try and set it via the ward mapping.  It should just retain how it was set
	$params=array();
	$params[1] = array( $objectId, 'Integer');
	$civicrm_value_gpew_party_information = CRM_Core_DAO::executeQuery( "SELECT * FROM civicrm_value_gpew_party_information WHERE entity_id=%1", $params );
	$civicrm_value_gpew_party_information->fetch();
	if($civicrm_value_gpew_party_information->override_local_party!=true){
	
		$params=array();
		$params[1] = array( $objectId, 'Integer');
		if(strlen($party_ids['local_party_contact_id'])){		
			$params[2] = array( $party_ids['local_party_contact_id'], 'Integer');
		} else {
			$params[2] = array( '', 'Date');
		}
		CRM_Core_DAO::executeQuery( "INSERT INTO `civicrm_value_gpew_party_information` SET `local_party_id`= %2, `entity_id` = %1 ON DUPLICATE KEY UPDATE `local_party_id`= %2", $params );
	}
	$params=array();
	$params[1] = array( $objectId, 'Integer');
	if(strlen($party_ids['regional_party_contact_id'])){		
		$params[2] = array( $party_ids['regional_party_contact_id'], 'Integer');
	} else {
		$params[2] = array( '', 'Date');
	}
	CRM_Core_DAO::executeQuery( "INSERT INTO `civicrm_value_gpew_party_information` SET `regional_party_id`= %2, `entity_id` = %1 ON DUPLICATE KEY UPDATE `regional_party_id`= %2", $params );
	
}


?>