<?php
function gpew_edit_own_contact_perm(){
  return array('View and edit own contact');
}

function gpew_edit_own_contact_user( $op, &$edit, &$account, $category = NULL ){
    if($op=='view'){
        $account->content['urls']=str_replace('&raquo; View Contact Record', '', $account->content['urls']);
    }
}


function gpew_edit_own_contact_civicrm_buildForm( $formName, &$form ){
  // if the form is the edit form
  if($formName=='CRM_Contact_Form_Contact'){
    gpew_edit_own_contact_check($form->_ContactId);
  }
}

function gpew_edit_own_contact_civicrm_pageRun( &$page ) {
  if(get_class($page)=='CRM_Contact_Page_View_Summary'){
    gpew_edit_own_contact_check($page->getVar('_contactId'));
  }
}

function gpew_edit_own_contact_check($contact_id){// and the contact is the logged in users contact
  if(user_access('View and edit own contact')){
    return;
  }

  $session = CRM_Core_Session::singleton();
  $userID = $session->get( 'userID' );
  if($userID!=$contact_id){
    return;
  }
  $params[1]=array($userID, 'Integer');
  $query= 'SELECT * FROM civicrm_relationship WHERE relationship_type_id IN (25,26,27,29) AND contact_id_a =%1';
  $result = CRM_Core_DAO::executeQuery($query, $params);
  if($result->N){
      return;   
  }

  $session->pushUserContext( CRM_Utils_System::url('civicrm', 'reset=1' ) );
  CRM_Core_Error::statusBounce( ts('Sorry, you are not allowed to view this page.') );
}
