<?php

// when a new memeber is added to CiviCRM

// look up the local and regional membership secretary email

// look up the contact id

function gpew_new_member_notification_civicrm_post( $op, $objectName, $objectId, &$objectRef ) {
	// gpew_capitation_batch_update();
	// exit;
	if($op != "create"){
		return;
	}
	if($objectName != "Membership"){
		return;
	}
	
	
	
	require_once 'CRM/Core/BAO/CustomValueTable.php';
	$params = array(
		'entityID' => $contact_id,
		'custom_51' => 1,
		'custom_52' => 1,
		);
		
	$party_ids=CRM_Core_BAO_CustomValueTable::getValues($params);
	print_r($party_ids);
	exit;
	require_once 'api/v2/Contact.php';	
	$contact=civicrm_contact_get($contact_params);
	$params['contact']=current($contact);
	$params['membership']['start_date'] = date ( 'd-m-Y', strtotime($objectRef->start_date));
	if(strlen($objectRef->end_date)){
		$params['membership']['end_date'] = date ( 'd-m-Y', strtotime($objectRef->end_date));		
	} else {
		$params['membership']['end_date'] = 'Life';
	}
	
//	echo gpew_new_member_notification_write_body($params);
//	exit;
}

// look up membership information

//send the emails, cc to office@greenparty.org.uk


function gpew_new_member_notification_write_body($params) {
	
	require_once 'CRM/Utils/Address.php';
	$address_block=CRM_Utils_Address::format($contact);
		
	$text="Dear membership secretary,

A new member has joined {$params['party']['organization_name']}.

{$contact[display_name]}

Address:
{$address_block}
Email: {$contact[email]}
Phone: {$contact[phone]}

Membership start date: {$params['membership']['start_date']}
Membership end date: {$params['membership']['end_date']}

";
	
	
	require_once 'api/v2/Contact.php';
	foreach($contactIDs as $id){
		$params=array('contact_id'=>$id);
		$contact=civicrm_contact_get($params);
		$values[$id]['contact.address_block']=nl2br(CRM_Utils_Address::format($contact[$id]));
	}
	
	return $text;
	
}